var hierarchy =
[
    [ "FlightKit.ControlsPrefs", "class_flight_kit_1_1_controls_prefs.html", null ],
    [ "MonoBehaviour", null, [
      [ "ButtonSound", "class_button_sound.html", null ],
      [ "ExitButton", "class_exit_button.html", null ],
      [ "FlightKit.ActivateOnTakeOff", "class_flight_kit_1_1_activate_on_take_off.html", null ],
      [ "FlightKit.AirplaneUserControl", "class_flight_kit_1_1_airplane_user_control.html", null ],
      [ "FlightKit.BackButton", "class_flight_kit_1_1_back_button.html", null ],
      [ "FlightKit.BoidMaster", "class_flight_kit_1_1_boid_master.html", null ],
      [ "FlightKit.BoidUnit", "class_flight_kit_1_1_boid_unit.html", null ],
      [ "FlightKit.ControlsSetting", "class_flight_kit_1_1_controls_setting.html", null ],
      [ "FlightKit.CrashController", "class_flight_kit_1_1_crash_controller.html", null ],
      [ "FlightKit.CrossFadeCanvasGroups", "class_flight_kit_1_1_cross_fade_canvas_groups.html", null ],
      [ "FlightKit.FadeInOnStart", "class_flight_kit_1_1_fade_in_on_start.html", null ],
      [ "FlightKit.Fader", "class_flight_kit_1_1_fader.html", null ],
      [ "FlightKit.FOVController", "class_flight_kit_1_1_f_o_v_controller.html", null ],
      [ "FlightKit.GameProgressTracker", "class_flight_kit_1_1_game_progress_tracker.html", null ],
      [ "FlightKit.KeyButton", "class_flight_kit_1_1_key_button.html", null ],
      [ "FlightKit.LevelCompleteController", "class_flight_kit_1_1_level_complete_controller.html", null ],
      [ "FlightKit.MenuFadeInController", "class_flight_kit_1_1_menu_fade_in_controller.html", null ],
      [ "FlightKit.MenuFadeOutController", "class_flight_kit_1_1_menu_fade_out_controller.html", null ],
      [ "FlightKit.MobileInputUIActivator", "class_flight_kit_1_1_mobile_input_u_i_activator.html", null ],
      [ "FlightKit.MusicController", "class_flight_kit_1_1_music_controller.html", null ],
      [ "FlightKit.PauseController", "class_flight_kit_1_1_pause_controller.html", null ],
      [ "FlightKit.PickupSphere", "class_flight_kit_1_1_pickup_sphere.html", null ],
      [ "FlightKit.SaturationController", "class_flight_kit_1_1_saturation_controller.html", null ],
      [ "FlightKit.SimplePropellerAnimator", "class_flight_kit_1_1_simple_propeller_animator.html", null ],
      [ "FlightKit.SoundButton", "class_flight_kit_1_1_sound_button.html", null ],
      [ "FlightKit.StartLevelController", "class_flight_kit_1_1_start_level_controller.html", null ],
      [ "FlightKit.TakeOffPublisher", "class_flight_kit_1_1_take_off_publisher.html", null ],
      [ "FlightKit.TiltInputCalibration", "class_flight_kit_1_1_tilt_input_calibration.html", null ],
      [ "FlightKit.UIEventsPublisher", "class_flight_kit_1_1_u_i_events_publisher.html", null ],
      [ "PlatformDependentActivator", "class_platform_dependent_activator.html", null ],
      [ "UnityStandardAssets.Vehicles.Aeroplane.AeroplaneController", "class_unity_standard_assets_1_1_vehicles_1_1_aeroplane_1_1_aeroplane_controller.html", null ]
    ] ]
];