var namespace_flight_kit =
[
    [ "ActivateOnTakeOff", "class_flight_kit_1_1_activate_on_take_off.html", "class_flight_kit_1_1_activate_on_take_off" ],
    [ "AirplaneUserControl", "class_flight_kit_1_1_airplane_user_control.html", "class_flight_kit_1_1_airplane_user_control" ],
    [ "BackButton", "class_flight_kit_1_1_back_button.html", "class_flight_kit_1_1_back_button" ],
    [ "BoidMaster", "class_flight_kit_1_1_boid_master.html", "class_flight_kit_1_1_boid_master" ],
    [ "BoidUnit", "class_flight_kit_1_1_boid_unit.html", "class_flight_kit_1_1_boid_unit" ],
    [ "ControlsPrefs", "class_flight_kit_1_1_controls_prefs.html", "class_flight_kit_1_1_controls_prefs" ],
    [ "ControlsSetting", "class_flight_kit_1_1_controls_setting.html", "class_flight_kit_1_1_controls_setting" ],
    [ "CrashController", "class_flight_kit_1_1_crash_controller.html", "class_flight_kit_1_1_crash_controller" ],
    [ "CrossFadeCanvasGroups", "class_flight_kit_1_1_cross_fade_canvas_groups.html", "class_flight_kit_1_1_cross_fade_canvas_groups" ],
    [ "FadeInOnStart", "class_flight_kit_1_1_fade_in_on_start.html", "class_flight_kit_1_1_fade_in_on_start" ],
    [ "Fader", "class_flight_kit_1_1_fader.html", null ],
    [ "FOVController", "class_flight_kit_1_1_f_o_v_controller.html", "class_flight_kit_1_1_f_o_v_controller" ],
    [ "GameProgressTracker", "class_flight_kit_1_1_game_progress_tracker.html", "class_flight_kit_1_1_game_progress_tracker" ],
    [ "KeyButton", "class_flight_kit_1_1_key_button.html", "class_flight_kit_1_1_key_button" ],
    [ "LevelCompleteController", "class_flight_kit_1_1_level_complete_controller.html", "class_flight_kit_1_1_level_complete_controller" ],
    [ "MenuFadeInController", "class_flight_kit_1_1_menu_fade_in_controller.html", "class_flight_kit_1_1_menu_fade_in_controller" ],
    [ "MenuFadeOutController", "class_flight_kit_1_1_menu_fade_out_controller.html", "class_flight_kit_1_1_menu_fade_out_controller" ],
    [ "MobileInputUIActivator", "class_flight_kit_1_1_mobile_input_u_i_activator.html", "class_flight_kit_1_1_mobile_input_u_i_activator" ],
    [ "MusicController", "class_flight_kit_1_1_music_controller.html", "class_flight_kit_1_1_music_controller" ],
    [ "PauseController", "class_flight_kit_1_1_pause_controller.html", "class_flight_kit_1_1_pause_controller" ],
    [ "PickupSphere", "class_flight_kit_1_1_pickup_sphere.html", "class_flight_kit_1_1_pickup_sphere" ],
    [ "SaturationController", "class_flight_kit_1_1_saturation_controller.html", null ],
    [ "SimplePropellerAnimator", "class_flight_kit_1_1_simple_propeller_animator.html", "class_flight_kit_1_1_simple_propeller_animator" ],
    [ "SoundButton", "class_flight_kit_1_1_sound_button.html", "class_flight_kit_1_1_sound_button" ],
    [ "StartLevelController", "class_flight_kit_1_1_start_level_controller.html", "class_flight_kit_1_1_start_level_controller" ],
    [ "TakeOffPublisher", "class_flight_kit_1_1_take_off_publisher.html", "class_flight_kit_1_1_take_off_publisher" ],
    [ "TiltInputCalibration", "class_flight_kit_1_1_tilt_input_calibration.html", "class_flight_kit_1_1_tilt_input_calibration" ],
    [ "UIEventsPublisher", "class_flight_kit_1_1_u_i_events_publisher.html", "class_flight_kit_1_1_u_i_events_publisher" ]
];